name: worddefiner-english-dictionary
version: 5.2.1
summary: The ultimate online English dictionary and thesaurus
description: WordDefiner is the ultimate online English dictionary and thesaurus app for iOS, iPadOS, and macOS. Learn the phonetic/phonemic transcription, pronunciation audio, and meanings, including synonyms and antonyms, based on part(s) speech for words that you look up with WordDefiner. Not just that, but you can also see statistically associated, similarly spelled, similar sounding, and rhyming words according to your query — even if the definition of your query can't be found. If that's not enough, WordDefiner even lets you see words that follow or precede the ones you look up, which nouns they typically modify, and which adjectives often modify them. And if that's still not enough, well, WordDefiner now provides hypernyms, hyponyms, holonyms, and meronyms!

confinement: strict
base: core22
grade: stable

slots:
  dbus-worddefiner-english-dictionary: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.nocturnaldevlab.worddefiner-english-dictionary # adjust accordingly to your app name and
    
apps:
  worddefiner-english-dictionary:
    command: worddefiner-english-dictionary
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-worddefiner-english-dictionary
parts:
  worddefiner-english-dictionary:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application